
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antho
 */
public class EndScreen extends javax.swing.JFrame {

    /**
     * Creates new form EndScreen
     */
    public EndScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCloseGameOver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaCharacterSummary = new javax.swing.JTextArea();
        lblGameOver = new javax.swing.JLabel();
        lblLegacy = new javax.swing.JLabel();
        btnRestartGame = new javax.swing.JButton();
        btnPrestige = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCloseGameOver.setText("Close game");
        btnCloseGameOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseGameOverActionPerformed(evt);
            }
        });

        areaCharacterSummary.setColumns(20);
        areaCharacterSummary.setLineWrap(true);
        areaCharacterSummary.setRows(6);
        areaCharacterSummary.setText("Level: " + String.valueOf(Player.getLevel()) + "\n" + "Experience: " + String.valueOf(Player.getCurrentEXP()) + "\n" + "Gold: " + String.valueOf(Player.getCurrentGold()) + "\n" + "Vitality: " + String.valueOf(Player.getMaxVitality()) + "\n" + "Power: " + String.valueOf(Player.getPower()) + "\n" + "Defense: " + String.valueOf(Player.getDefense()) + "\n" + "Stage: " + String.valueOf(Player.getBossCount()));
        areaCharacterSummary.setToolTipText("");
        areaCharacterSummary.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaCharacterSummary);

        lblGameOver.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblGameOver.setForeground(new java.awt.Color(255, 204, 0));
        lblGameOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGameOver.setText("You have completed your quest");

        lblLegacy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLegacy.setText("Legacy of " + Global.getPlayerName());

        btnRestartGame.setText("Restart game");
        btnRestartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartGameActionPerformed(evt);
            }
        });

        btnPrestige.setText("Prestige Character");
        btnPrestige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestigeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRestartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCloseGameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPrestige, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLegacy, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblGameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLegacy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestige)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestartGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseGameOver))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseGameOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseGameOverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseGameOverActionPerformed

    private void btnRestartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartGameActionPerformed
        // TODO add your handling code here:
        Player defaultCharacter = new Player();
        defaultCharacter = null;

        StartMenu StartMenuScreen = new StartMenu();
        StartMenuScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnRestartGameActionPerformed

    private void btnPrestigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestigeActionPerformed
        // allows player to keep fighting monsters for an even greater challenge
        Player.setPrestige(Player.getPrestige() + 1);
       
        int prestigeConfirm = JOptionPane.showConfirmDialog(null,"Are you sure you wish to prestige? Choosing this will allow you to continue fighting monsters, and will increase the difficulty of the final boss.", "Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(prestigeConfirm == JOptionPane.YES_OPTION){
            MainMenu MainMenuScreen = new MainMenu();
            MainMenuScreen.show();
            this.dispose();
        } else if (prestigeConfirm == JOptionPane.NO_OPTION){
               EndScreen endScreen = new EndScreen();
               endScreen.show();
               this.dispose();
        }
    }//GEN-LAST:event_btnPrestigeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaCharacterSummary;
    private javax.swing.JButton btnCloseGameOver;
    private javax.swing.JButton btnPrestige;
    private javax.swing.JButton btnRestartGame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGameOver;
    private javax.swing.JLabel lblLegacy;
    // End of variables declaration//GEN-END:variables
}
