
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antho
 */
public class Equipment extends javax.swing.JFrame {

    /**
     * Creates new form EquipmentScreen
     */
    public Equipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWeaponSlot = new javax.swing.JLabel();
        lblHeadSlot = new javax.swing.JLabel();
        lblChestSlot = new javax.swing.JLabel();
        lblLegsSlot = new javax.swing.JLabel();
        txtHeadSlot = new javax.swing.JTextField();
        txtChestSlot = new javax.swing.JTextField();
        txtLegsSlot = new javax.swing.JTextField();
        txtWeaponSlot = new javax.swing.JTextField();
        btnInvFromEquip = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaEquipStatus1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaEquipStatus2 = new javax.swing.JTextArea();
        btnMainFromEquip = new javax.swing.JButton();
        btnCloseEquipment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWeaponSlot.setText("Weapon");

        lblHeadSlot.setText("Head");

        lblChestSlot.setText("Chest");

        lblLegsSlot.setText("Legs");

        btnInvFromEquip.setText("Go To Inventory");
        btnInvFromEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvFromEquipActionPerformed(evt);
            }
        });

        areaEquipStatus1.setColumns(1);
        areaEquipStatus1.setLineWrap(true);
        areaEquipStatus1.setRows(5);
        areaEquipStatus1.setText("Level\nExperience\nGold\nHealth\nMana");
        jScrollPane1.setViewportView(areaEquipStatus1);

        areaEquipStatus2.setColumns(1);
        areaEquipStatus2.setLineWrap(true);
        areaEquipStatus2.setRows(5);
        areaEquipStatus2.setText("Power\nWisdom\nDefense\nAgility\n");
        jScrollPane2.setViewportView(areaEquipStatus2);

        btnMainFromEquip.setText("Main Menu");
        btnMainFromEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainFromEquipActionPerformed(evt);
            }
        });

        btnCloseEquipment.setText("Close");
        btnCloseEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseEquipmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWeaponSlot)
                    .addComponent(txtWeaponSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChestSlot)
                    .addComponent(lblHeadSlot)
                    .addComponent(lblLegsSlot)
                    .addComponent(txtHeadSlot)
                    .addComponent(txtChestSlot)
                    .addComponent(txtLegsSlot, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnMainFromEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvFromEquip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnCloseEquipment))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeadSlot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeadSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeaponSlot)
                            .addComponent(lblChestSlot))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeaponSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChestSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLegsSlot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLegsSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainFromEquip)
                    .addComponent(btnInvFromEquip)
                    .addComponent(btnCloseEquipment)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseEquipmentActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseEquipmentActionPerformed

    private void btnMainFromEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainFromEquipActionPerformed
        // TODO add your handling code here:
        MainMenu MainMenuScreen = new MainMenu();
        MainMenuScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnMainFromEquipActionPerformed

    private void btnInvFromEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvFromEquipActionPerformed
        // TODO add your handling code here:
        Inventory InventoryScreen = new Inventory();
        InventoryScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnInvFromEquipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEquipStatus1;
    private javax.swing.JTextArea areaEquipStatus2;
    private javax.swing.JButton btnCloseEquipment;
    private javax.swing.JButton btnInvFromEquip;
    private javax.swing.JButton btnMainFromEquip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChestSlot;
    private javax.swing.JLabel lblHeadSlot;
    private javax.swing.JLabel lblLegsSlot;
    private javax.swing.JLabel lblWeaponSlot;
    private javax.swing.JTextField txtChestSlot;
    private javax.swing.JTextField txtHeadSlot;
    private javax.swing.JTextField txtLegsSlot;
    private javax.swing.JTextField txtWeaponSlot;
    // End of variables declaration//GEN-END:variables
}
