
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antho
 */
public class FinalJourneyMenu extends javax.swing.JFrame {
    
    int count = 0;
    
    int monsterDefenseCheck;
    int playerDefenseCheck;
    /**
     * Creates new form FinalJourneyMenu
     */
    public FinalJourneyMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdPotion = new javax.swing.JRadioButton();
        lblPotionsHeld = new javax.swing.JLabel();
        rdMegaPotion = new javax.swing.JRadioButton();
        lblMegaPotionsHeld = new javax.swing.JLabel();
        rdMaxPotion = new javax.swing.JRadioButton();
        lblMaxPotionsHeld = new javax.swing.JLabel();
        btnHeal = new javax.swing.JButton();
        btnStartBattle = new javax.swing.JButton();
        btnCloseJourney = new javax.swing.JButton();
        lblPlayerName = new javax.swing.JLabel();
        prgPlayerHealth = new javax.swing.JProgressBar();
        lblEnemyName = new javax.swing.JLabel();
        prgEnemyHealth = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaAttackMessage = new javax.swing.JTextArea();
        lblPlayerHealth = new javax.swing.JLabel();
        lblEnemyHealth = new javax.swing.JLabel();
        btnAttack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdPotion.setText("Potion");

        lblPotionsHeld.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPotionsHeld.setText("Held: " + Player.getPotionsHeld());

        rdMegaPotion.setText("Mega Potion");

        lblMegaPotionsHeld.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMegaPotionsHeld.setText("Held: " + Player.getMegaPotionsHeld());

        rdMaxPotion.setText("Max Potion");

        lblMaxPotionsHeld.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaxPotionsHeld.setText("Held: " + Player.getMaxPotionsHeld());

        btnHeal.setBackground(new java.awt.Color(153, 255, 153));
        btnHeal.setText("Heal");
        btnHeal.setEnabled(false);
        btnHeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealActionPerformed(evt);
            }
        });

        btnStartBattle.setText("Start");
        btnStartBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartBattleActionPerformed(evt);
            }
        });

        btnCloseJourney.setText("Close");
        btnCloseJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseJourneyActionPerformed(evt);
            }
        });

        lblPlayerName.setText(Global.getPlayerName());

        prgPlayerHealth.setForeground(new java.awt.Color(0, 255, 0));
        prgPlayerHealth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prgPlayerHealth.setOpaque(true);
        prgPlayerHealth.setString("10%");

        lblEnemyName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEnemyName.setText(Monster.getMonsterName());

        prgEnemyHealth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prgEnemyHealth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        areaAttackMessage.setColumns(20);
        areaAttackMessage.setLineWrap(true);
        areaAttackMessage.setRows(5);
        areaAttackMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaAttackMessage);

        lblPlayerHealth.setText("Health: " + Player.getCurrentVitality() + " / " + Player.getMaxVitality());

        lblEnemyHealth.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEnemyHealth.setText("Health: " + Monster.getCurrentVitality() + " / " + Monster.getMaxVitality());

        btnAttack.setBackground(new java.awt.Color(255, 153, 153));
        btnAttack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAttack.setText("Attack");
        btnAttack.setEnabled(false);
        btnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlayerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnemyName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayerHealth)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(prgPlayerHealth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdMaxPotion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblMaxPotionsHeld))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdMegaPotion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addComponent(lblMegaPotionsHeld))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdPotion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPotionsHeld))
                                    .addComponent(btnHeal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAttack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStartBattle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCloseJourney, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnemyHealth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prgEnemyHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlayerName)
                            .addComponent(lblEnemyName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prgPlayerHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prgEnemyHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartBattle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerHealth)
                    .addComponent(lblEnemyHealth))
                .addGap(2, 2, 2)
                .addComponent(btnAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdPotion)
                            .addComponent(lblPotionsHeld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdMegaPotion)
                            .addComponent(lblMegaPotionsHeld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdMaxPotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaxPotionsHeld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHeal, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnCloseJourney))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealActionPerformed
        // TODO add your handling code here:
        if (rdPotion.isSelected()) {
            if (Player.getPotionsHeld() > 0) {
                Player.setCurrentVitality(Player.getCurrentVitality() + 5);

                Player.setPotionsHeld(Player.getPotionsHeld() - 1);

                if (Player.getCurrentVitality() > Player.getMaxVitality()) {
                    Player.setCurrentVitality(Player.getMaxVitality());
                }

                prgPlayerHealth.setValue(Player.getCurrentVitality());
                lblPlayerHealth.setText("Health: " + Player.getCurrentVitality() + " / " + Player.getMaxVitality());
                lblPotionsHeld.setText("Held: " + Player.getPotionsHeld());

                areaAttackMessage.setText("Your potion heals you for 5 health points.");

                btnHeal.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "You have no more potions left!");
            }
        }

        if (rdMegaPotion.isSelected()) {
            if (Player.getMegaPotionsHeld() > 0) {
                Player.setCurrentVitality(Player.getCurrentVitality() + 10);

                Player.setPotionsHeld(Player.getMegaPotionsHeld() - 1);

                if (Player.getCurrentVitality() > Player.getMaxVitality()) {
                    Player.setCurrentVitality(Player.getMaxVitality());
                }

                prgPlayerHealth.setValue(Player.getCurrentVitality());
                lblPlayerHealth.setText("Health: " + Player.getCurrentVitality() + " / " + Player.getMaxVitality());
                lblPotionsHeld.setText("Held: " + Player.getMegaPotionsHeld());

                areaAttackMessage.setText("Your mega potion heals you for 20 health points.");

                btnHeal.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "You have no more mega potions left!");
            }
        }

        if (rdMaxPotion.isSelected()) {
            if (Player.getMaxPotionsHeld() > 0) {
                Player.setCurrentVitality(Player.getMaxVitality());

                Player.setPotionsHeld(Player.getPotionsHeld() - 1);

                if (Player.getCurrentVitality() > Player.getMaxVitality()) {
                    Player.setCurrentVitality(Player.getMaxVitality());
                }

                prgPlayerHealth.setValue(Player.getCurrentVitality());
                lblPlayerHealth.setText("Health: " + Player.getCurrentVitality() + " / " + Player.getMaxVitality());
                lblPotionsHeld.setText("Held: " + Player.getMaxPotionsHeld());

                areaAttackMessage.setText("Your max potion fully heals you.");

                btnHeal.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "You have no more max potions left!");
            }
        }
    }//GEN-LAST:event_btnHealActionPerformed

    private void btnStartBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartBattleActionPerformed
        // TODO add your handling code here:
        areaAttackMessage.setText("");

        Monster finalBoss = new Monster("finalBoss",100,100,1,1,15,15);

        lblEnemyName.setText(Monster.getMonsterName());
        lblEnemyHealth.setText("Health: " + Monster.getCurrentVitality() + " / " + Monster.getMaxVitality());

        btnAttack.setEnabled(true);
        btnHeal.setEnabled(true);

        prgPlayerHealth.setMaximum(Player.getMaxVitality());
        prgPlayerHealth.setValue(Player.getCurrentVitality());

        prgEnemyHealth.setMaximum(Monster.getMaxVitality());
        prgEnemyHealth.setValue(Monster.getCurrentVitality());

        btnStartBattle.setEnabled(false);
    }//GEN-LAST:event_btnStartBattleActionPerformed

    private void btnCloseJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseJourneyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseJourneyActionPerformed

    private void btnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttackActionPerformed
        // TODO add your handling code here:
        monsterDefenseCheck = Player.getPower() - Monster.getDefense();
        
        if (monsterDefenseCheck < 1) {
            monsterDefenseCheck = 1;
        }
        
        Monster.setCurrentVitality(Monster.getCurrentVitality() - monsterDefenseCheck);
        prgEnemyHealth.setValue(Monster.getCurrentVitality());
        
        playerDefenseCheck = Monster.getPower() - Player.getDefense();
        
        if (playerDefenseCheck < 1) {
            playerDefenseCheck = 1;
        }
        
        Player.setCurrentVitality(Player.getCurrentVitality() - playerDefenseCheck);
        prgPlayerHealth.setValue(Player.getCurrentVitality());
        
        if (Monster.getCurrentVitality() < 0) {
            Monster.setCurrentVitality(0);
        } else {
            Monster.setCurrentVitality(Monster.getCurrentVitality());
        }
        
        if (Player.getCurrentVitality() < 0) {
                Player.setCurrentVitality(0);
        } else {
            Player.setCurrentVitality(Player.getCurrentVitality());
        }
        
        btnHeal.setEnabled(true);
        
        areaAttackMessage.setText("You have dealt " + monsterDefenseCheck + " damage to " + Monster.getMonsterName() + ". In return, " + Monster.getMonsterName() + " deals " + playerDefenseCheck + " damage to you.");
        
        lblPlayerHealth.setText("Health: " + Player.getCurrentVitality() + " / " + Player.getMaxVitality());
        lblEnemyHealth.setText("Health: " + Monster.getCurrentVitality() + " / " + Monster.getMaxVitality());

        if (Player.getCurrentVitality() == 0) {
            JOptionPane.showMessageDialog(null, "You have been defeated!");

            Player.setCurrentVitality(Player.getMaxVitality());

            GameOverScreen GameOverScreen = new GameOverScreen();
            GameOverScreen.show();
            this.dispose();
        }

        if (Monster.getCurrentVitality() == 0) {
            areaAttackMessage.setText("You have defeated " + Monster.getMonsterName() + "! You recieve " + Monster.getDroppedEXP() + " experience points and " + Monster.getDroppedGold() + " gold. Continue to the next monster.");
            Player.setCurrentEXP(Player.getCurrentEXP() + Monster.getDroppedEXP());
            Player.setCurrentGold(Player.getCurrentGold() + Monster.getDroppedGold());

            btnAttack.setEnabled(false);
            btnHeal.setEnabled(false);

            Monster defeatedMonster = new Monster();
            defeatedMonster = null;

            if (Player.getCurrentEXP() >= 100){
                int vitalityIncrease =  3 + (int)(Math.random() * (8 - 3));
                int powerIncrease =  0 + (int)(Math.random() * (3 - 0));
                int defenseIncrease =  0 + (int)(Math.random() * (3 - 0));

                JOptionPane.showMessageDialog(null, "You have leveled up! Your level increased by 1, vitality increased by " + vitalityIncrease + ", power increased by " + powerIncrease + ", and defense increased by " + defenseIncrease + "!");

                Player.setLevel(Player.getLevel() + 1);
                Player.setMaxVitality(Player.getMaxVitality() + vitalityIncrease);
                Player.setPower(Player.getPower() + powerIncrease);
                Player.setDefense(Player.getDefense() + defenseIncrease);

                Player.setCurrentEXP(Player.getCurrentEXP() - 100);
            }
            
            EndScreen endScreen = new EndScreen();
            endScreen.show();
            this.dispose();

        }
    }//GEN-LAST:event_btnAttackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalJourneyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalJourneyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalJourneyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalJourneyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalJourneyMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAttackMessage;
    private javax.swing.JButton btnAttack;
    private javax.swing.JButton btnCloseJourney;
    private javax.swing.JButton btnHeal;
    private javax.swing.JButton btnStartBattle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnemyHealth;
    private javax.swing.JLabel lblEnemyName;
    private javax.swing.JLabel lblMaxPotionsHeld;
    private javax.swing.JLabel lblMegaPotionsHeld;
    private javax.swing.JLabel lblPlayerHealth;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPotionsHeld;
    private static javax.swing.JProgressBar prgEnemyHealth;
    private static javax.swing.JProgressBar prgPlayerHealth;
    private javax.swing.JRadioButton rdMaxPotion;
    private javax.swing.JRadioButton rdMegaPotion;
    private javax.swing.JRadioButton rdPotion;
    // End of variables declaration//GEN-END:variables
}
