
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antho
 */
public class MainMenu extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnToShop = new javax.swing.JButton();
        btnCloseMain = new javax.swing.JButton();
        btnToEquipment = new javax.swing.JButton();
        btnToDungeon = new javax.swing.JButton();
        btnToInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaStatus = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        btnFinalBoss = new javax.swing.JButton();
        lblStage = new javax.swing.JLabel();
        lblPrestige = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnToShop.setBackground(new java.awt.Color(153, 153, 255));
        btnToShop.setText("Go to Shop");
        btnToShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToShopActionPerformed(evt);
            }
        });

        btnCloseMain.setText("Close");
        btnCloseMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMainActionPerformed(evt);
            }
        });

        btnToEquipment.setBackground(new java.awt.Color(153, 255, 153));
        btnToEquipment.setText("Go to Equipment");
        btnToEquipment.setToolTipText("");
        btnToEquipment.setEnabled(false);
        btnToEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToEquipmentActionPerformed(evt);
            }
        });

        btnToDungeon.setBackground(new java.awt.Color(255, 153, 153));
        btnToDungeon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnToDungeon.setText("Enter Dungeon");
        btnToDungeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToDungeonActionPerformed(evt);
            }
        });

        btnToInventory.setBackground(new java.awt.Color(153, 255, 153));
        btnToInventory.setText("Go to Inventory");
        btnToInventory.setToolTipText("");
        btnToInventory.setEnabled(false);
        btnToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToInventoryActionPerformed(evt);
            }
        });

        areaStatus.setColumns(1);
        areaStatus.setLineWrap(true);
        areaStatus.setRows(6);
        areaStatus.setText("Level: " + String.valueOf(Player.getLevel()) + "\n" + "Experience: " + String.valueOf(Player.getCurrentEXP()) + "/100" + "\n" + "Gold: " + String.valueOf(Player.getCurrentGold()) + "\n" + "Vitality: " + String.valueOf(Player.getMaxVitality()) + "\n" + "Power: " + String.valueOf(Player.getPower()) + "\n" + "Defense: " + String.valueOf(Player.getDefense())
        );
        areaStatus.setToolTipText("");
        jScrollPane1.setViewportView(areaStatus);

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStatus.setText("Status for " + Global.getPlayerName());

        btnFinalBoss.setText("Final Challenge");
        btnFinalBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalBossActionPerformed(evt);
            }
        });

        lblStage.setText("Stage: " + (Player.getBossCount() + 1));

        lblPrestige.setText("Prestige: " + Player.getPrestige());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCloseMain))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnToDungeon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnToInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnToShop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnToEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStage)
                                        .addComponent(btnFinalBoss))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPrestige)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFinalBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrestige)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStage))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnToDungeon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToShop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnToEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseMain))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMainActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMainActionPerformed

    private void btnToInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToInventoryActionPerformed
        // TODO add your handling code here:
        Inventory InventoryScreen = new Inventory();
        InventoryScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToInventoryActionPerformed

    private void btnToEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToEquipmentActionPerformed
        // TODO add your handling code here:
        Equipment EquipmentScreen = new Equipment();
        EquipmentScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToEquipmentActionPerformed

    private void btnToDungeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToDungeonActionPerformed
        // TODO add your handling code here:
        DungeonMenu DungeonMenuScreen = new DungeonMenu();
        DungeonMenuScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToDungeonActionPerformed

    private void btnToShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToShopActionPerformed
        // TODO add your handling code here:
        ShopMenu ShopMenuScreen = new ShopMenu();
        ShopMenuScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToShopActionPerformed

    private void btnFinalBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalBossActionPerformed
        // allows the final boss to only be available after 10 bosses
        if (Player.getBossCount() >= 10) {
            FinalDungeonMenu FinalDungeonMenuScreen = new FinalDungeonMenu();
            FinalDungeonMenuScreen.show();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "An unseeable force prevents you from entering the final dungeon. You may need to train more before you accept this challenge.");
        }
    }//GEN-LAST:event_btnFinalBossActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStatus;
    private javax.swing.JButton btnCloseMain;
    private static javax.swing.JButton btnFinalBoss;
    private javax.swing.JButton btnToDungeon;
    private javax.swing.JButton btnToEquipment;
    private javax.swing.JButton btnToInventory;
    private javax.swing.JButton btnToShop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrestige;
    private javax.swing.JLabel lblStage;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
