
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antho
 */
public class MainMenu extends javax.swing.JFrame {
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnToShop = new javax.swing.JButton();
        btnCloseMain = new javax.swing.JButton();
        btnToEquipment = new javax.swing.JButton();
        btnToJourney = new javax.swing.JButton();
        btnToInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaStatus1 = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnToShop.setBackground(new java.awt.Color(153, 153, 255));
        btnToShop.setText("Go to Shop");
        btnToShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToShopActionPerformed(evt);
            }
        });

        btnCloseMain.setText("Close");
        btnCloseMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMainActionPerformed(evt);
            }
        });

        btnToEquipment.setBackground(new java.awt.Color(153, 255, 153));
        btnToEquipment.setText("Go to Equipment");
        btnToEquipment.setToolTipText("");
        btnToEquipment.setEnabled(false);
        btnToEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToEquipmentActionPerformed(evt);
            }
        });

        btnToJourney.setBackground(new java.awt.Color(255, 153, 153));
        btnToJourney.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnToJourney.setText("Journey");
        btnToJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToJourneyActionPerformed(evt);
            }
        });

        btnToInventory.setBackground(new java.awt.Color(153, 255, 153));
        btnToInventory.setText("Go to Inventory");
        btnToInventory.setToolTipText("");
        btnToInventory.setEnabled(false);
        btnToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToInventoryActionPerformed(evt);
            }
        });

        areaStatus1.setColumns(1);
        areaStatus1.setLineWrap(true);
        areaStatus1.setRows(4);
        areaStatus1.setText("Level: " + String.valueOf(Player.getLevel()) + "\n" + "Vitality: " + String.valueOf(Player.getMaxVitality()) + "\n" + "Power: " + String.valueOf(Player.getPower()) + "\n" + "Defense: " + String.valueOf(Player.getDefense())
        );
        areaStatus1.setToolTipText("");
        jScrollPane1.setViewportView(areaStatus1);

        lblStatus.setText("Status for " + Global.getPlayerName());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseMain, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnToJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnToShop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnToJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToShop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnToEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnToInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCloseMain))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMainActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseMainActionPerformed

    private void btnToInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToInventoryActionPerformed
        // TODO add your handling code here:
        Inventory InventoryScreen = new Inventory();
        InventoryScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToInventoryActionPerformed

    private void btnToEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToEquipmentActionPerformed
        // TODO add your handling code here:
        Equipment EquipmentScreen = new Equipment();
        EquipmentScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToEquipmentActionPerformed

    private void btnToJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToJourneyActionPerformed
        // TODO add your handling code here:
        JourneyMenu JourneyMenuScreen = new JourneyMenu();
        JourneyMenuScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToJourneyActionPerformed

    private void btnToShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToShopActionPerformed
        // TODO add your handling code here:
        ShopMenu ShopMenuScreen = new ShopMenu();
        ShopMenuScreen.show();
        this.dispose();
    }//GEN-LAST:event_btnToShopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStatus1;
    private javax.swing.JButton btnCloseMain;
    private javax.swing.JButton btnToEquipment;
    private javax.swing.JButton btnToInventory;
    private javax.swing.JButton btnToJourney;
    private javax.swing.JButton btnToShop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
